name: chessnutdriver
description: A chessnut-Chessboard Driver written in pure Dart
version: 0.0.4
repository: https://github.com/mono424/chessnutdriver
homepage: https://khad.im

environment:
  sdk: ">=2.7.0 <3.0.0"
